app:
  name: "E-commerce Backend"
  version: "1.0.0"
  environment: "development"
  debug: true

server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  
database:
  max_open_conns: 25
  max_idle_conns: 5
  max_lifetime: 300s

redis:
  pool_size: 10
  min_idle_conns: 5

security:
  bcrypt_cost: 10
  rate_limit_per_minute: 100
